import { TitleSlide } from './TitleSlide';
import { BioSlide } from './BioSlide';
import { TimelineSlide } from './TimelineSlide';
import { ClaudeCodeSlide } from './ClaudeCodeSlide';
import { BreakOutOfCodingSlide } from './BreakOutOfCodingSlide';
import { SoftwareFactorySlide } from './SoftwareFactorySlide';
import { WhatIsSkillSlide } from './WhatIsSkillSlide';
import { ImportantSlide } from './ImportantSlide';
import { SkillMarketplaceSlide } from './SkillMarketplaceSlide';
import { MetaSkillsSlide } from './MetaSkillsSlide';
import { AutoApproveHookSlide } from './AutoApproveHookSlide';
import { EveryOrgRightNowSlide } from './EveryOrgRightNowSlide';
import { AIInnovatorCurveSlide } from './AIInnovatorCurveSlide';
import { InceptionPatternsSlide } from './InceptionPatternsSlide';
import { SkillsActivatorSlide } from './SkillsActivatorSlide';
import { SkillsMetricsSlide } from './SkillsMetricsSlide';
import { AgentsSlide } from './AgentsSlide';
import { AgentWorkflowSlide } from './AgentWorkflowSlide';
import { AgentTracesSlide } from './AgentTracesSlide';
import { AgentExampleSlide } from './AgentExampleSlide';
import { IndustryPatternsSlide } from './IndustryPatternsSlide';
import { HumanAiEngSlide } from './HumanAiEngSlide';
import { AutonomousAiSlide } from './AutonomousAiSlide';
import { ChallengeAssumptionsSlide } from './ChallengeAssumptionsSlide';
import { FinalSlide } from './FinalSlide';

export const slides = [TitleSlide, BioSlide, TimelineSlide, EveryOrgRightNowSlide, InceptionPatternsSlide, BreakOutOfCodingSlide, ImportantSlide, SoftwareFactorySlide, WhatIsSkillSlide, SkillMarketplaceSlide, MetaSkillsSlide, AutoApproveHookSlide, AIInnovatorCurveSlide, SkillsActivatorSlide, SkillsMetricsSlide, AgentsSlide, AgentWorkflowSlide, AgentTracesSlide, AgentExampleSlide, IndustryPatternsSlide, AutonomousAiSlide, HumanAiEngSlide, ChallengeAssumptionsSlide, ClaudeCodeSlide, FinalSlide];
